dist: trusty
sudo: false
language: python
python:
  - '3.5'

jdk:
  - oraclejdk8

addons:
  sonarqube:
    organization: "timetable"
    token:
      secure: "$SONAR_TOKEN"
branches:
  only:
  - master
  - desenvolvimento

script:
  - sonar-scanner
