# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-21 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=50)),
                ('cod_disc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DiscMinistrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('cod_prof', models.CharField(max_length=12)),
                ('disc_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=20)),
                ('cod_turma', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='discministrada',
            name='profId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Professor'),
        ),
    ]
