# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('turno', models.CharField(choices=[(b'0', b'Matutino'), (b'1', b'Vespertino'), (b'2', b'Noturno')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('carga_horaria', models.TextField(choices=[(b'0', b'1 aula'), (b'1', b'2 aulas'), (b'2', b'3 aulas'), (b'3', b'4 aulas'), (b'4', b'5 aulas'), (b'5', b'6 aulas')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina_ministrada',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('codigo_disciplina', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina_turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_ministrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Disciplina_ministrada')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=70)),
                ('codigo', models.CharField(max_length=12)),
                ('restricao_dia_semana', models.CharField(choices=[(b'0', b'Nenhuma'), (b'2', b'Segunda'), (b'3', b'Ter\xc3\xa7a'), (b'4', b'Quarta'), (b'5', b'Quinta'), (b'6', b'Sexta')], max_length=1)),
                ('restricao_horario', models.TextField(choices=[(b'0', b'Nenhuma'), (b'1', b'Primeira'), (b'2', b'Segunda'), (b'3', b'Terceira'), (b'4', b'Quarta'), (b'5', b'Quinta'), (b'6', b'Sexta'), (b'7', b'Todas')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina_turma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Turma'),
        ),
        migrations.AddField(
            model_name='disciplina_ministrada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Professor'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Escola'),
        ),
    ]
