# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('turno', models.CharField(choices=[(b'0', b'Matutino'), (b'1', b'Vespertino'), (b'2', b'Noturno')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina_ministrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(max_length=50)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('codigo', models.CharField(max_length=12)),
                ('restricao_dia_semana', models.CharField(choices=[(b'0', b'Segunda'), (b'1', b'Ter\xc3\xa7a'), (b'2', b'Quarta'), (b'3', b'Quinta'), (b'4', b'Sexta')], max_length=1)),
                ('restricao_horario', models.CharField(choices=[(b'0', b'Primeira'), (b'1', b'Segunda'), (b'2', b'Terceira'), (b'3', b'Quarta'), (b'4', b'Quinta'), (b'5', b'Sexta')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=12)),
                ('turno', models.CharField(choices=[(b'0', b'Matutino'), (b'1', b'Vespertino'), (b'2', b'Noturno')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina_ministrada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Professor'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.Escola'),
        ),
    ]
