# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='nome',
        ),
        migrations.AddField(
            model_name='turma',
            name='turma',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turma',
            name='cod_turma',
            field=models.CharField(max_length=50),
        ),
    ]
